### ISSUE TITLE
Methods for logging to users.

### ISSUE THREAD

**Issue by nkomarn** [Firestarter/Kerosene#18]
Create a way to get default strings for errors prefixes, etc. This can possibly be an enum.

**Comment by thatgoofydev** [comment]
How about a static string?

```java
player.sendMessage(Prefixes.ERROR + "Some error message");
```

they can even be loaded from the config.

:stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes:
